config/routes.rb
Artaround::Application.routes.draw do
  resources :arts do
    post :comment, :on => :member
    post :submit, :on => :member
    post :add_photo, :on => :member
    post :flag, :on => :member
    get :index, :on => :collection
    post :manage_link ,:on => :collection
    get :destroy_link, :on => :member
    get :filter_category, :on => :collection

  end

  namespace :admin do
    resources :stats, only:[:index] do
      collection do
        get :tags
        get :categories
        get :cities
        get :artists
      end
    end
    resources :art_imports, controller: 'arts_import', only: [:show, :new, :create]
    resources :arts do
      resources :comments do
        post :delete, :on => :member
        post :unapprove, :on => :member
        post :approve, :on => :member
      end
      resources :photos
      post :manage_link ,:on => :collection
      get :destroy_link, :on => :member
      resources :submissions, :only => [:destroy] do
        get :approve, :on => :member
      end
    end

    resources :tags
    resources :artists
    resources :countries
    resources :events
    resources :commissioners
    get 'tag/:id' => 'tags#destroy', as: :trash_tag
    get 'artist/:id' => 'artists#destroy', as: :trash_artist
    get 'country/:id' => 'countries#destroy', as: :trash_country
  end

  namespace :api do
    scope '/v1' do
      resources :arts, :except => [:new, :edit] do
        member do
          post :photos
          post :comments
        end
      end

      get "/neighborhoods" => "arts#neighborhoods_api"
      get "/categories" => "arts#categories_api"
      get "/tags" => "arts#tags_api"
    end
  end

  get "/new_art_photo" => "arts#new_art_photo", :as => "new_art_photo"
  post "/create_art_photo" => "arts#create_art_photo", :as => "create_art_photo"

  get "/admin" => "admin/arts#index", :as => "admin"

  get "/contact" => "home#contact"
  get "/about" => "home#about"
  get "/faq" => "home#faq"

  post "/contact/send" => "home#send_contact", :as => "send_contact"

  get "/map" => "arts#map", :as => "map"
  get "/events/:slug" => "arts#map"
  get "/autocomplete_commissioners" => "home#autocomplete_commissioners"

  get "/tag/:id" => "tag#show" ,:as => "tag"
  get "/artist/:id" => "artist#show" ,:as => "artist"
  get "/category/:id" => "category#show" ,:as => 'category'
  root :to => "arts#index"
end

app/models/tag.rb
class Tag
  include Mongoid::Document
  belongs_to :art, optional: true

  field :name, type: String
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::AdminController
  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new tag_params
    if @tag.save
      redirect_to admin_tags_path, notice: 'Successfully Created Tag.'
    else
      render :new
    end
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    @tag.name = params[:tag][:name]
    if @tag.save
      redirect_to admin_tags_path, notice: 'Tag edits successfully saved!'
    else
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to admin_tags_path
  end

  protected

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/tag_controller.rb
class TagController < ApplicationController
	def show
    
    if params[:sort] == 'popular'
      sort = :total_visits
    else
      sort = :created_at
    end
      @arts = Art.approved.where(tag: params[:id]).desc(sort).page(params[:page]).per(25)
      @arts_old = Art.approved.where(tag_id: params[:id]).desc(sort).page(params[:page]).per(25)
    respond_to do |format|
      format.html {render "arts/index"}
    end
	end
end

app/helpers/tag_helper.rb
module TagHelper
end

app/views/admin/tags/index.html.erb
<div id="pageMain" class="admin">

  <div id="fullColumn">
    <div id="titleContent">
      <h2>Admin Area</h2>
    </div>
  </div>

  <div id="ltColumn">
    <h3>Tags list</h3>
    <ul>
      <% @tags.each do |tag| %>
        <li>
          <%= link_to tag.name, admin_tag_path(tag) %>
        </li>
      <% end %>
    </ul>
  </div>

  <div id="rtColumn">
    <h3>
      Tag (<%= link_to 'New', new_admin_tag_path %>)
    </h3>
  </div>
</div>

app/views/admin/tags/new.html.erb
<div id="pageMain" class="admin">

<div id="fullColumn">
    <div id="titleContent">
        <h2>Admin Area</h2>
    </div>
</div>
<%= form_for @tag, :url => admin_tags_path  do |f| %>
	<ul>
	<li>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</li>
	<li>
		<button class="submitBtn" type="submit">
		    <span>Submit</span>
		</button>
	</li>
	</ul>
<%end%>

</div>

app/views/admin/tags/show.html.erb
<div id="pageMain" class="admin">

<div id="fullColumn">
    <div id="titleContent">
        <h2>Admin Area</h2>
    </div>
</div>
<%= link_to "Delete this tag" ,admin_trash_tag_path(@tag) %>
<%= form_for @tag, :url => admin_tag_path(@tag) do |f| %>
	<ul>
	<li>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</li>
	<li>
		<button class="submitBtn" type="submit">
		    <span>Submit</span>
		</button>
	</li>
	</ul>
<%end%>

</div>