config/routes.rb
Artaround::Application.routes.draw do
  resources :arts do
    post :comment, :on => :member
    post :submit, :on => :member
    post :add_photo, :on => :member
    post :flag, :on => :member
    get :index, :on => :collection
    post :manage_link ,:on => :collection
    get :destroy_link, :on => :member
    get :filter_category, :on => :collection

  end

  namespace :admin do
    resources :stats, only:[:index] do
      collection do
        get :tags
        get :categories
        get :cities
        get :artists
      end
    end
    resources :art_imports, controller: 'arts_import', only: [:show, :new, :create]
    resources :arts do
      resources :comments do
        post :delete, :on => :member
        post :unapprove, :on => :member
        post :approve, :on => :member
      end
      resources :photos
      post :manage_link ,:on => :collection
      get :destroy_link, :on => :member
      resources :submissions, :only => [:destroy] do
        get :approve, :on => :member
      end
    end

    resources :tags
    resources :artists
    resources :countries
    resources :events
    resources :commissioners
    get 'tag/:id' => 'tags#destroy', as: :trash_tag
    get 'artist/:id' => 'artists#destroy', as: :trash_artist
    get 'country/:id' => 'countries#destroy', as: :trash_country
  end

  namespace :api do
    scope '/v1' do
      resources :arts, :except => [:new, :edit] do
        member do
          post :photos
          post :comments
        end
      end

      get "/neighborhoods" => "arts#neighborhoods_api"
      get "/categories" => "arts#categories_api"
      get "/tags" => "arts#tags_api"
    end
  end

  get "/new_art_photo" => "arts#new_art_photo", :as => "new_art_photo"
  post "/create_art_photo" => "arts#create_art_photo", :as => "create_art_photo"

  get "/admin" => "admin/arts#index", :as => "admin"

  get "/contact" => "home#contact"
  get "/about" => "home#about"
  get "/faq" => "home#faq"

  post "/contact/send" => "home#send_contact", :as => "send_contact"

  get "/map" => "arts#map", :as => "map"
  get "/events/:slug" => "arts#map"
  get "/autocomplete_commissioners" => "home#autocomplete_commissioners"

  get "/tag/:id" => "tag#show" ,:as => "tag"
  get "/artist/:id" => "artist#show" ,:as => "artist"
  get "/category/:id" => "category#show" ,:as => 'category'
  root :to => "arts#index"
end

app/controllers/admin/arts_controller.rb
class Admin::ArtsController < Admin::AdminController
  before_action :load_art, :only => [:show, :update, :destroy]

  def index
    @arts = Art.desc(:created_at).all
    @events = Event.desc(:created_at).all
    @commissioners = Commissioner.desc(:created_at).all
  end

  def show
  end

  def destroy
    @art.destroy
    redirect_to admin_path
  end

  def update
    # some attributes are protected from mass assignment, pluck them out
    @art.commissioned = params[:art].delete 'commissioned'
    @art.approved = params[:art].delete 'approved'

    # special case - slug
    # can't do a validates_presence_of for weird reasons, so validate here
    slug = params[:art].delete 'slug'
    if slug.present?
      @art._slugs = [slug]
    end

    latitude = params[:art].delete 'latitude'
    longitude = params[:art].delete 'longitude'
    # remove special case
    latitude = ["Click on Map", nil].include?(latitude) ? nil : latitude.to_f
    longitude = ["Click on Map", nil].include?(longitude) ? nil : longitude.to_f
    @art.location = [latitude, longitude]

    @art.attributes = art_params
    @art.category.reject!(&:blank?)
    @art.artist.reject!(&:blank?)
    # @art.art_link.create( params[:art][:art_link_attributes]['0']) if params[:art][:art_link_attributes]['0'][:title].present?

    if @art.save
      redirect_to admin_art_path(@art), :notice => "Successfully updated art piece."
    else
      # always reset the slug so that URLs don't get messed up
      @art.slug = params[:id]
      render :show
    end
  end

  def manage_link
    # debugger
    if params[:link_url_id].present?
      art_link = ArtLink.find(params[:link_url_id])
      art_link.title = params[:title]
      art_link.link_url = params[:url]
      art_link.save
    else
      art_link = ArtLink.create(title: params[:title],link_url: params[:url],art_id: params[:art_id])
    end
    # redirect_to :back
    render :json => { :success => true }
  end

  def destroy_link
    art_link = ArtLink.find params[:id]
    art = art_link.art
    art_link.delete
    redirect_to art
    #render :json => { :success => true }
  end

  protected

  def art_params
    params.require(:art).permit(:featured, :commisioned, :approved, :title,
                                :website, :year, :latitude, :logitude,
                                :location_description, :description, :event_id,
                                artist: [], category: [], tag: [])
  end

  def load_art
    @art = Art.find(params[:id])
    @events = Event.all
  end

end

app/controllers/api/arts_controller.rb
class Api::ArtsController < Api::ApiController
  before_action :load_art, :only => :show

  def index
    render :json => json_for_arts
  end

  def create
    # Drop the Rails-related parameters
    location = params[:location]
    vals = params.reject { |k, v| %w[ controller action format _method location ].include?(k) }

    # Clean the Params as the ios app encodes them.
    vals = ParamsCleaner.clean(vals.permit(:artist, :category, :description,
                                           :location_description, :year, :title,
                                           :website, :commisioned_by))
    # Create a new Art object with the values received from the API client.
    # Some values are protected from mass-assignment, so they will need to
    # be set manually.
    if vals[:category]
      vals[:category] = vals[:category].split(',')
    end

    art = Art.new(vals)

    art.approved = true # auto-approve, would default to false otherwise

    if location
      latitude = location[0].to_f
      longitude = location[1].to_f
      art.location = [latitude, longitude]
    end

    unless vals[:commissioned_by].blank?
      @commissioner = Commissioner.where({:name => /^#{vals[:commissioned_by]}/i}).first
      if @commissioner.nil?
        @commissioner = Commissioner.create(:name => vals[:commissioned_by])
      end
    end

    respond_to do |format|
      format.json do
        # If the art is successfully saved, send back the JSON representation
        # of the art. Otherwise, send back the errors and a Bad Request
        # status code.
        if art.save
          AdminMailer.new_art(art).deliver
          unless @commissioner.nil?
            @commissioner.arts.push(art)
            @commissioner.save
          end
          render :json => { :success => art.slug }
        else
          Rails.logger.info "Could not save art: #{art.errors.inspect}"
          render :json => art.errors, :status => 400
        end
      end
    end
  end

  def photos
    art = Art.find(params[:id])

    # Send back a 404 message if the art was not found. Since
    # this is an API, no body is required.
    head :not_found and return unless art

    photo = create_photo art, params[:file], params[:photo_attribution_text], params[:photo_attribution_url]

    if photo.save
      AdminMailer.new_photo(art).deliver
      art.inc photo_count: 1
      render json: json_for_art(art)
    else
      render json: { success: false, errors: photo.errors.messages.values.flatten }, status: 500
    end
  end

  def show
    @art.inc api_visits: 1
    @art.inc total_visits: 1
    render json: {
      art: json_for_art(@art)
    }
  end

  def update
    art = Art.find(params[:id])

    # Send back a 404 message if the art was not found. Since
    # this is an API, no body is required.
    head :not_found and return unless art

    data = params.reject { |k, v| %w[ controller action format id _method location slug title website ].include?(k) }
    # Clean the Params as the ios app encodes them.
    data = ParamsCleaner.clean(data.permit(:artist, :category, :description,
                                           :location_description, :year, :title,
                                           :website, :commisioned_by))

    submission = art.submissions.build(data)

    respond_to do |format|
      format.json do
        if submission.save
          AdminMailer.new_art_info(art, submission).deliver
          render json: { success: true }
        else
          Rails.logger.info "Could not save submission: #{submission.errors.inspect}"
          render json: { success: false }, status: 400
        end
      end
    end
  end

  def comments
    art = Art.find(params[:id])

    # Send back a 404 message if the art was not found. Since
    # this is an API, no body is required.
    head :not_found and return unless art

    vals = {
      name: params[:name],
      email: params[:email],
      url: params[:url],
      text: params[:text]
    }
    # Clean the Params as the ios app encodes them.
    vals = ParamsCleaner.clean(vals)

    comment = art.comments.build(vals)
    comment.ip_address = request.ip

    respond_to do |format|
      format.json do
        # Respond with 200 if the comment was posted successfully or tell the
        # client it was a BadRequest otherwise
        if comment.save
          AdminMailer.new_comment(art, params[:name], params[:text]).deliver
          render json: { success: true }
        else
          Rails.logger.info "Comment for art #{art.id} could not be saved: #{comment.errors.inspect}"
          render json: { success: false }
        end
      end
    end
  end

  def neighborhoods_api
    render json: neighborhoods.to_json
  end

  def categories_api
    render json: categories.to_json
  end

  def tags_api
    render json: tags.to_json
  end

  protected

  def load_art
    @art = Art.approved.find(params[:id])
  end
end

app/helpers/arts_helper.rb
module ArtsHelper
  def pretty_print_tags submission
    return [] if submission.tag.nil?
    submission.tag.reject(&:blank?)
  end

  def pretty_print_categories submission
    return [] if submission.category.nil?
    return [submission.category] if submission.category.is_a?(String)
    submission.category.reject(&:blank?)
  end

  def pretty_print_artist submission
    return '' if submission.artist.nil?
    submission.artist
  end

  def comment_url comment
    if comment.url.include? "http://"
      comment.url
    else
      "http://#{comment.url}"
    end
  end
end

app/views/admin/arts/index.html.erb
<div id="pageMain" class="admin">

<div id="fullColumn">
    <div id="titleContent">
        <h2>Admin Area</h2>
    </div>
</div>

<div id="ltColumn">
    <h3>Art pieces</h3>
    <ul>
        <% @arts.each do |art| %>
            <li>
                <%= link_to art.title, admin_art_path(art) %>
            </li>
        <% end %>
    </ul>
</div>

<div id="rtColumn">
    <h3>
        Events
        (<%= link_to "New", new_admin_event_path %>)
    </h3>
    <ul>
        <% @events.each do |event| %>
            <li>
                <%= link_to event.name, admin_event_path(event) %>
            </li>
        <% end %>
    </ul>
    <h3>Commissioners</h3>
    <ul>
        <% @commissioners.each do |com| %>
            <li>
                <%= link_to com.name, admin_commissioner_path(com) %>
            </li>
        <% end %>
    </ul>
</div>

<div class="clear"></div>

</div>

app/views/admin/arts/show.html.erb
<% content_for :footer do %>
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyBdug7_rlFIe_C9eQdKgEZHX9Cbx-wYBi0&sensor=false&callback=loadMaps"></script>
<% end %>

<% content_for :head do %>
  <script type="text/javascript">
    var geocoder;
    var map;
    var searchMarker;

    <% if @art.category.present? %>
        var art_category = "<%=@art.category[0] %>"
    <%else%>
      var art_category = "Unknown"
    <%end%>

    <% if @art.tag.present? %>
        var art_tag = "<%=@art.tag[0]%>"
    <%else%>
      var art_tag = "Unknown"
    <%end%>

    function loadMaps() {

      <% if @art.latitude and @art.longitude %>
        var start = new google.maps.LatLng(<%= @art.latitude %>, <%= @art.longitude %>);
      <% else %>
        // dupont circle
        var start = new google.maps.LatLng(38.90940, -77.04382);
      <% end %>

      map = new google.maps.Map(document.getElementById("map_canvas"), {
        zoom: 15,
        center: start,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        mapTypeControl: false
      });

      <% if @art.latitude and @art.longitude %>
        // initialize
        updateLocation(start);
      <% end %>

      google.maps.event.addListener(map, "click", function(event) {
        updateLocation(event.latLng);
      });

      geocoder = new google.maps.Geocoder();
      $("input#search_button").click(function() {
        var query = $("input#search_text").val();
        geocoder.geocode({
          address: query,
          region: "us"
        }, function(results, status) {
          if (status == google.maps.GeocoderStatus.OK) {
            var location = results[0].geometry.location;

            map.setZoom(15);
            updateLocation(location);
            map.panTo(location);
          }
        });
      });

    }

    function updateLocation(location) {
      if (searchMarker)
        searchMarker.setMap(null);

      searchMarker = new google.maps.Marker({position: location});
      searchMarker.setMap(map);

      art_category = art_category.toLowerCase();
      art_tag = art_tag.toLowerCase();
      if ( art_category == "catalog" || art_tag == "catalog") {
        icon = "teal.png"
      }
      else if ( art_category == "street art host spots" ||  art_tag == "street art host spots") {
        icon = "yellow.png"
      }
      else if ( art_category == "museum" || art_tag == "museum" ||  art_category == "art gallery" || art_tag == "art gallery" ||  art_category == "outdoor gallery" || art_tag == "outdoor gallery" ||  art_category == "gallery" || art_tag == "gallery") {
        icon = "blue.png"
      }
      else if ( art_category == "artchive" || art_tag == "artchive") {
        icon = "grey.png"
      }
      else {
        icon = "red.png"
      }
      var pinImage = "/images/pins/"+icon;
      searchMarker.setIcon(pinImage);



      $("input#art_latitude").val(location.lat());
      $("input#art_longitude").val(location.lng());

      searchMarker.setDraggable(true);
      google.maps.event.addListener(searchMarker, "dragend", function(event) {
        updateLocation(event.latLng);
      });
    }

    $(function() {
      if ($("input#art_latitude").val() == "")
        $("input#art_latitude").val("Click on Map");
      if ($("input#art_longitude").val() == "")
        $("input#art_longitude").val("Click on Map");

      $("a.delete.art").click(function() {
        if (confirm("Delete this art piece FOREVER?"))
          $("form.delete.art").submit();
        return false;
      });

      $("a.delete.photo").click(function() {
        if (confirm("Delete this photo FOREVER?"))
          $(this).parents("form.photo.delete").submit();
        return false;
      })
      $('#art_category').chosen({allow_single_deselect:true});
      $('#art_tag').chosen({allow_single_deselect:true});
      $('#art_artist').chosen({allow_single_deselect:true});
      $('#art_tag_id').chosen({allow_single_deselect:true});
    });
  </script>
<% end %>

<div id="pageMain" class="admin">

<form class="art delete form" action="<%= admin_art_path @art %>" method="post">
  <input type="hidden" name="_method" value="delete" />
</form>

<div id="fullColumn">
  <div id="titleContent">
    <h2>
      <%= @art.title %>
      <a style="float: right" href="<%= admin_path %>">&laquo; Back</a>
    </h2>
    <div class="admin_landing_link">
      <%= link_to "Landing page", art_path(@art) %>
      <%= link_to "Delete this art", "#", :class => "art delete" %>
    </div>
  </div>
</div>

<div id="ltColumn">

  <%= form_for @art, :url => admin_art_path(@art) do |f| %>
    <% if @art.errors.any? %>
      <% @art.errors.full_messages.each do |message| %>
        <div class="errors">
          <%= message %>
        </div>
      <% end %>
    <% end %>

    <ul>
      <li>
        <%= f.label :featured %>
        <%= f.check_box :featured %>
      </li>
      <li>
        <%= f.label :commissioned %>
        <%= f.check_box :commissioned %>
      </li>
      <li>
        <%= f.label :approved %>
        <%= f.check_box :approved %>
      </li>
      <li>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </li>
      <li>
        <%= f.label :slug %>
        <%= f.text_field :slug %>
      </li>
      <li>
        <%= f.label :website %>
        <%= f.text_field :website %>
      </li>
      <li>
        <%= f.label :category %>
        <%= f.select :category, categories, {}, {:multiple => true, :style => "width: 350px"}  %>
      </li>
      <li>
        <%= f.label :year %>
        <%= f.text_field :year %>
      </li>
      <li>
        <%= f.label :latitude %>
        <%= f.text_field :latitude %>
      </li>
      <li>
        <label for="art_tag">Tags</label>
        <%= f.select :tag, Tag.all.collect(&:name), {}, { :multiple => true, :style => "width: 350" } %>
      </li>
      <li>
        <%= f.label :longitude %>
        <%= f.text_field :longitude %>
      </li>
      <li>
        <%= f.label :artist, "Artist(s) blah" %>
        <%#= f.text_field :artist, value: "joel" %>
        <%= f.select :artist, Artist.all.collect(&:name), {}, {:multiple => true, :style => "width: 350px"}  %>
      </li>
      <li>
        <%= f.label :location_description %>
        <%= f.text_area :location_description %>
      </li>
      <li>
        <%= f.label :description %>
        <%= f.text_area :description %>
      </li>

      <%@art.art_link.each do |al|%>
        <li>
          <%= link_to al.title , al.link_url%>
          <span style="float: right;">
          <%= link_to "" , destroy_link_admin_art_path(al),:class => "delete_icon" ,:remote => true %>
          <%= link_to "" ,"javascript:void(0)",:class => "edit_icon" ,:art_link_id => al.id ,:art_link_title => al.title ,:art_link_url => al.link_url %>
          </span>
        </li>
      <%end%>

      <%#= f.fields_for :art_link ,@art.art_link.new do |l| %>
      <%#= form_for @art.art_link.new , remote: true do |l| %>
      <li>
        <%= label_tag :title ,"Link Title"%>
        <%= text_field_tag :title %>
      </li>
      <li>
        <%= label_tag :link_url,"Link Url" %>
        <%= text_field_tag :link_url %>
        <%= hidden_field_tag :link_url_id %>
        <%= button_tag "Save link",:type => "button",:class=>"submitBtn" ,:id => "link_submit"%>
        <%= button_tag "Cancel",:type => "button",:class=>"" ,:id => "link_cancel" %>
      </li>

      <%#end%>

      <li>
        <%= f.label :event_id %>
        <%= f.collection_select :event_id, @events, :id, :name, :include_blank => "----" %>
      </li>
      <li>
        <button class="submitBtn" type="submit">
            <span>Submit</span>
        </button>
      </li>
    </ul>
  <% end %>

  <% @art.photos.each do |photo| %>
    <%= render "admin/photos/show", :art => @art, :photo => photo %>
  <% end %>

</div>

<div id="rtColumn">
  <div id="search_box">
    <label id="search_text_label">Map Search:
      <input type="text" id="search_text" />
    </label>
    <input type="submit" id="search_button" value="Search" />
  </div>
  <div id="map_canvas"></div>

  <!-- Submissions -->
  <br/>
  <h3>Edit Submissions</h3>
  <% @art.submissions.each do |submission| %>
    <div class="submission">
      <b>Tag:</b> <%= pretty_print_tags submission %><br/>
      <b>Category:</b> <%= pretty_print_categories submission %><br/>
      <b>Artist:</b> <%= pretty_print_artist submission %><br/>
      <b>Year:</b> <%= submission.year %><br/>
      <b>Description:</b> <%= submission.description %><br/>
      <b>Location Description</b>: <%= submission.location_description %><br/>
      <% if submission.link? %>
        <b>Link</b>: <%= submission.link_title %> [<%= link_to submission.link_url, submission.link_url %>]<br/>
      <% end %>

      <div class="tools">
        <% unless submission.applied? %>
          <%= link_to "Apply Submission", approve_admin_art_submission_path(@art, submission) %>,
        <% end %>
        <%= link_to "Delete Submission", admin_art_submission_path(@art, submission), method: 'delete' %>
      </div>
    </div>
  <% end %>
</div>

<div class="clear"></div>
</div>


<script>
  $("#link_submit").on("click",function(){
    // alert("testig")
    $.ajax({
      type: 'post',
      data: {art_id: '<%=@art.id%>' ,title: $("input#title").val() ,url: $("input#link_url").val() ,link_url_id: $("input#link_url_id").val()},
      url: '<%=manage_link_admin_arts_path%>',
      success: function (response) {
        // return false;
        $('input#title').val('');
        $('input#link_url').val('');
        $('input#link_url_id').val('');
        location.reload();
      }
    });
  });

  $('.edit_icon').on('click', function(){
    $('input#title').val($(this).attr("art_link_title"));
    $('input#link_url').val($(this).attr("art_link_url"));
    $('input#link_url_id').val($(this).attr("art_link_id"));
    $("#link_cancel").show();
  });

  $("#link_cancel").on("click",function(){
    $('input#title').val('');
    $('input#link_url').val('');
    $('input#link_url_id').val('');
    $("#link_cancel").hide();
  });
</script>