config/routes.rb
Artaround::Application.routes.draw do
  resources :arts do
    post :comment, :on => :member
    post :submit, :on => :member
    post :add_photo, :on => :member
    post :flag, :on => :member
    get :index, :on => :collection
    post :manage_link ,:on => :collection
    get :destroy_link, :on => :member
    get :filter_category, :on => :collection

  end

  namespace :admin do
    resources :stats, only:[:index] do
      collection do
        get :tags
        get :categories
        get :cities
        get :artists
      end
    end
    resources :art_imports, controller: 'arts_import', only: [:show, :new, :create]
    resources :arts do
      resources :comments do
        post :delete, :on => :member
        post :unapprove, :on => :member
        post :approve, :on => :member
      end
      resources :photos
      post :manage_link ,:on => :collection
      get :destroy_link, :on => :member
      resources :submissions, :only => [:destroy] do
        get :approve, :on => :member
      end
    end

    resources :tags
    resources :artists
    resources :countries
    resources :events
    resources :commissioners
    get 'tag/:id' => 'tags#destroy', as: :trash_tag
    get 'artist/:id' => 'artists#destroy', as: :trash_artist
    get 'country/:id' => 'countries#destroy', as: :trash_country
  end

  namespace :api do
    scope '/v1' do
      resources :arts, :except => [:new, :edit] do
        member do
          post :photos
          post :comments
        end
      end

      get "/neighborhoods" => "arts#neighborhoods_api"
      get "/categories" => "arts#categories_api"
      get "/tags" => "arts#tags_api"
    end
  end

  get "/new_art_photo" => "arts#new_art_photo", :as => "new_art_photo"
  post "/create_art_photo" => "arts#create_art_photo", :as => "create_art_photo"

  get "/admin" => "admin/arts#index", :as => "admin"

  get "/contact" => "home#contact"
  get "/about" => "home#about"
  get "/faq" => "home#faq"

  post "/contact/send" => "home#send_contact", :as => "send_contact"

  get "/map" => "arts#map", :as => "map"
  get "/events/:slug" => "arts#map"
  get "/autocomplete_commissioners" => "home#autocomplete_commissioners"

  get "/tag/:id" => "tag#show" ,:as => "tag"
  get "/artist/:id" => "artist#show" ,:as => "artist"
  get "/category/:id" => "category#show" ,:as => 'category'
  root :to => "arts#index"
end

app/views/layouts/_addthis.html.erb
<div class="addthis_toolbox addthis_default_style">
	<span class='st_facebook' displayText='Facebook'></span>
	<span class='st_twitter' displayText='Tweet'></span>
	<span class='st_pinterest' displayText='Pinterest'></span>
	<span class='st_googleplus' displayText='Google +1'></span>
</div>

app/views/layouts/_flash.html.erb
<% [:notice, :alert].each do |msg| %>
  <% if flash[msg] %>
    <div class="flash <%= msg %>">
      <%= flash[msg] %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!-- <%= Rails.version %> -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
  <head>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta property="og:site_name" content="ArtAround" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <title>ArtAround</title>

    <script type="text/javascript" src="http://use.typekit.com/rxr6ppr.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>

    <%= stylesheet_link_tag 'main' %>
    <%= stylesheet_link_tag 'stats' %>
    <%= stylesheet_link_tag 'chosen' %>

    <%= javascript_include_tag 'jquery-1.7.1.min' %>
    <%= javascript_include_tag 'delete' %>
    <%= javascript_include_tag 'dragdealer' %>
    <%= javascript_include_tag 'chosen.jquery.min' %>
    <%= javascript_include_tag 'bootstrap.min' %>
    <%= javascript_include_tag 'jquery.isotope.min.js' %>
    <%= javascript_include_tag 'jquery.infinitescroll.js' %>
    <%= javascript_include_tag 'jquery.lazyload.min.js' %>

    <%= yield :head %>

  </head>

  <body class="<%= content_for :body_class %>">
    <div id="headerWrapper">
      <header>
      <div class="social-links-container fullsite">
        <a target="_blank" href="https://www.facebook.com/ArtAround/">
          <img src="/images/icons/facebook.png" />
        </a>
        <a target="_blank" href="https://twitter.com/artaround">
          <img src="/images/icons/twitter.png" />
        </a>
        <a target="_blank" href="https://www.instagram.com/theartaroundus/">
          <img src="/images/icons/instagram.png" />
        </a>
        <a target="_blank" href="http://eepurl.com/F40Sn">
          <img src="/images/icons/mail.png" />
        </a>
      </div>
        <div>
          <ul class="about-links">
            <li class="nav_link"><a target="_blank" href="https://itunes.apple.com/us/app/artaround/id463678249?mt=8">Get the App⇗</a></li>
            <li class="nav_link"><a target="_blank" href="http://arrow.theartaround.us/">Magazine</a></li>
            <li class="nav_link no-mobile"><a href="<%= contact_path %>">Contact Us</a></li>
            <li class="nav_link"><a href="<%= faq_path %>">FAQ</a></li>
            <li class="nav_link"><a target="_blank" href="https://www.fracturedatlas.org/site/fiscal/profile?id=16343">Give</a></li>
            <li class="nav_link"><a href="<%= about_path %>">About</a></li>
          </ul>
        </div>
        <div class="clear"></div>
        <h1>
          <a class="mainLogo" href="/">
            <img src="/images/logo.png" />
            <span class="tag-line">a living archive of art in public spaces</span>
          </a>
          <a class="mobileLogo" href="/"><img src="/images/logo_mobile_new.png" /></a>
        </h1>
        <div>
          <% if @artworks_count.present?%>
            <div class="counts-container no-mobile">
              <span class="count yellow">
                <%= @artworks_count %>
              </span>
              <span class="count-label">
                artworks
              </span>
              <span class="count red">
                <%= @artist_count %>
              </span>
              <span class="count-label">
                artists
              </span>
              <span class="count blue">
                56
              </span>
              <span class="count-label no-margin">
                cities
              </span>
            </div>
          <%end%>
        </div>
        <div class="formNavContainer">
          <nav>
            <ul class="main_nav">
              <% tabs = yield(:tabs) %>

              <% if tabs.present? %>
                <%= tabs %>
              <% else %>
                <li id="map_link">
                  <a id="map" href="/" href="#">Home</a>
                </li>
              <% end %>

              <li id="addArt_link">
                <%= link_to "Add Art", new_art_photo_path, :id => "addArt" %>
              </li>
              <% if params[:controller].include? 'admin/' %>
              <li id="addArt_link">
                <%= link_to "Import Art", new_admin_art_import_path, :id => "import" %>
              </li>
              <li id="tags_link">
                <%= link_to "Tags", admin_tags_path, :id => "tags" %>
              </li>
              <li id="artists_link">
                <%= link_to "Artists", admin_artists_path, :id => "artists" %>
              </li>
              <li id="countries_link">
                <%= link_to "Countries", admin_countries_path, :id => "countries" %>
              </li>
              <li>
                <%= link_to "Stats", admin_stats_path, id: "stats" %>
              </li>
              <script>$(".formNavContainer").css("width","500px")</script>
              <%end%>
            </ul>
          </nav>
        </div>
        <div class="clear"></div>
      </header>
    </div>

    <%= yield %>
    <div id="footerWrap">
      <footer>
        <small class="cclicense">
          <span class="ccicons"></span>
          All photos are licensed with a <a href="http://creativecommons.org/licenses/by-nc/3.0/">Creative Commons Attribution-NonCommercial</a> license.
        </small>
      </footer>
      <div class="social-links-container mobile">
        <a target="_blank" href="https://www.facebook.com/ArtAround/">
          <img src="/images/icons/facebook.png" />
        </a>
        <a target="_blank" href="https://twitter.com/artaround">
          <img src="/images/icons/twitter.png" />
        </a>
        <a target="_blank" href="https://www.instagram.com/theartaroundus/">
          <img src="/images/icons/instagram.png" />
        </a>
        <a target="_blank" href="http://eepurl.com/F40Sn">
          <img src="/images/icons/mail.png" />
        </a>
      </div>
    </div>
    <%= yield :footer %>

    <% if Rails.env == "production" %>
      <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
              (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-41817858-1', 'theartaround.us');
          ga('send', 'pageview');

      </script>
    <% end %>
    <script>
      $(window).load(function(){

        var $optionSets = $('#options .option-set'),
            $optionLinks = $optionSets.find('a');

        $optionLinks.click(function(){
          var $this = $(this);
          // don't proceed if already selected
          if ( $this.hasClass('selected') ) {
            return false;
          }
          var $optionSet = $this.parents('.option-set');
          $optionSet.find('.selected').removeClass('selected');
          $this.addClass('selected');

          // make option object dynamically, i.e. { filter: '.my-filter-class' }
          var options = {},
              key = $optionSet.attr('data-option-key'),
              value = $this.attr('data-option-value');
          // parse 'false' as false boolean
          value = value === 'false' ? false : value;
          options[ key ] = value;
          if ( key === 'layoutMode' && typeof changeLayoutMode === 'function' ) {
            // changes in layout modes need extra logic
            changeLayoutMode( $this, options )
          } else {
            // otherwise, apply new options
            $container.isotope( options );
          }

          return false;
        });
        $('#sort-by a').click(function(){
          //removes class from all items to "clear" the class from your menu
          $('#sort-by a').removeClass("current");

          //adds the class to whichever item you clicked
          $(this).addClass("current");
        });
        $(function() {

            var $container = $('#art-list'),
                $select = $('#filters select');

            $container.isotope({
                itemSelector: '.isotope-item'
            });

        });
      });
    </script>
  </body>
</html>